# fly.toml app configuration file generated for ramadan-iftar-booking on 2025-01-21T02:41:50-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ramadan-iftar-booking'
primary_region = 'dfw'

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  GOOGLE_APPLICATION_CREDENTIALS = "/app/secrets.json"


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  protocol = "tcp"

[[services.ports]]
  handlers = ["http"]
  port = 80

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
