# fly.toml app configuration file generated for ramadan-iftar-booking on 2025-01-21T02:41:50-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ramadan-iftar-booking'
primary_region = 'dfw'

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  GOOGLE_APPLICATION_CREDENTIALS = "/app/secrets.json"
  DATABASE_URL = "https://bookiftar2025-default-rtdb.firebaseio.com/"

[http_service]
  internal_port = 8080
  force_https = true

[[services.ports]]
  handlers = ["http"]
  port = 80

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
